import = [
"~/.config/alacritty/themes/themes/nord.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[window]
dimensions = { columns = 112, lines = 28 }
position = { x = 70, y = 150 }
padding = { x = 15, y = 20 }
decorations = "None"
resize_increments = true
opacity = 1
blur = true
option_as_alt = "Both"

[font]
normal = { family = "RobotoMONO Nerd Font", style = "Regular" }
size = 13
offset = { x = 0, y = 0 }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On"}
blink_interval = 500
unfocused_hollow = false

[keyboard]
bindings = [
{ key = "n", mods = "Control|Alt", action = "CreateNewWindow" },
{ key = "c", mods = "Control", action = "CopySelection" },
{ key = "v", mods = "Control", action = "PasteSelection" },
{ key = "q", mods = "Control|Alt", action = "Quit" },
{ key = "f", mods = "Control|Alt", action = "ToggleFullscreen" },
{ key = "m", mods = "Control|Alt", action = "Minimize" },
]


